### ISSUE TITLE
Remote 플로우에서 select 버튼 더블 클릭 이슈

### ISSUE THREAD

**Issue by jeekpark** [space-pong/SpacePong#51]

**Comment by Taeil-Nam** [comment]
- dmin님께서 Local game 플레이에서도 더블 클릭시 게임 두 개 실행되는 issue 발견.

remote 뿐만 아니라, 다른 페이지들도 영향 받는 issue로 보임.

**Comment by Taeil-Nam** [comment]
[Fix: 더블 클릭 문제 해결](https://github.com/space-pong/SpacePong/commit/6cf4f1d86b696461ad31853a3e665145f0725251)
현재 클릭 시간 - 이전 클릭 시간 < 1초인 경우, 클릭 이벤트 무시

Issue solved.
