### ISSUE TITLE
OTP 페이지에서 창 종료 후 재접속하면 메인화면 접근

### ISSUE THREAD

**Issue by jeekpark** [space-pong/SpacePong#52]
*시크릿모드에서 테스트 안됨

**Comment by Taeil-Nam** [comment]
Backend와 API로 통신하도록 로직 수정 완료.

이슈는 아직 해결되지 않음.

**Comment by Taeil-Nam** [comment]
1. Backend DB에 사용자 OTP 정보가 없는 경우 (최초 OTP 갱신의 경우)
- 이슈 발생 하지 않음.

2. Backend DB에 사용자 OTP 정보가 남아 있는 경우 (OTP 갱신 만료 전)
- 이슈 발생.

---

해결 방안
- 로그아웃 또는 창 종료시, DB의 사용자 OTP 지우는 요청 하면 될 것 같습니다. (otpDelete 전용 API 추가 필요) 
- 로그아웃은 버튼 눌렀을 때 이벤트 등록시키면 될 것 같고, 창 종료, 탭 종료, 브라우저 종료 등은 beforeunload 이벤트로 감지 가능하다고 합니다.

```javascript
window.addEventListener('beforeunload', (event) => {
  const data = { message: 'User is leaving the page' };
  const url = '/api/logout';

  // sendBeacon을 사용하여 데이터 전송
  navigator.sendBeacon(url, JSON.stringify(data));

  console.log('브라우저가 닫히기 전에 sendBeacon으로 데이터 전송');
});
```

**Comment by Taeil-Nam** [comment]
beforeunload 이벤트가 새로고침에도 영향줘서, 이때마다 OTP 기록 지우면 새로고침 할 때마다 otp 쳐야해요..

해결 방안은 회의할 때 정하는 걸로..

**Comment by Taeil-Nam** [comment]
Issue sovled.
